-- Create invoices table for billing history (manual payment flow)
CREATE TABLE IF NOT EXISTS invoices (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    workspace_id BIGINT NOT NULL,
    subscription_id BIGINT DEFAULT NULL,
    requested_by BIGINT DEFAULT NULL,
    plan_code VARCHAR(50) NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'PKR',
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    billing_cycle VARCHAR(10) NOT NULL,
    payment_method VARCHAR(30) DEFAULT NULL,
    payment_proof_url VARCHAR(500) DEFAULT NULL,
    transaction_id VARCHAR(100) DEFAULT NULL,
    admin_notes VARCHAR(500) DEFAULT NULL,
    period_start DATETIME DEFAULT NULL,
    period_end DATETIME DEFAULT NULL,
    due_date DATETIME DEFAULT NULL,
    reviewed_by BIGINT DEFAULT NULL,
    reviewed_at DATETIME DEFAULT NULL,
    paid_at DATETIME DEFAULT NULL,
    rejected_at DATETIME DEFAULT NULL,
    rejection_reason VARCHAR(500) DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME DEFAULT NULL,
    deleted_by BIGINT DEFAULT NULL,
    created_by BIGINT DEFAULT NULL,
    updated_by BIGINT DEFAULT NULL,
    FOREIGN KEY (workspace_id) REFERENCES workspaces(id),
    FOREIGN KEY (subscription_id) REFERENCES workspace_subscriptions(id),
    FOREIGN KEY (requested_by) REFERENCES users(id),
    INDEX idx_invoice_workspace (workspace_id),
    INDEX idx_invoice_status (status),
    INDEX idx_invoice_requested_by (requested_by)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
