-- HR Leave Types
CREATE TABLE IF NOT EXISTS hr_leave_types (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    workspace_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(32) NOT NULL,
    description TEXT,
    default_days INT NOT NULL DEFAULT 0,
    is_paid BOOLEAN DEFAULT TRUE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted_at DATETIME NULL,
    deleted_by BIGINT NULL,
    INDEX idx_hr_leave_types_workspace (workspace_id),
    INDEX idx_hr_leave_types_active (workspace_id, is_active),
    CONSTRAINT fk_hr_leave_types_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id),
    UNIQUE KEY uk_hr_leave_types_code_workspace (workspace_id, code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- HR Leave Balances
CREATE TABLE IF NOT EXISTS hr_leave_balances (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    workspace_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    leave_type_id BIGINT NOT NULL,
    request_year INT NOT NULL,
    total_days DECIMAL(5,1) NOT NULL DEFAULT 0,
    used_days DECIMAL(5,1) NOT NULL DEFAULT 0,
    pending_days DECIMAL(5,1) NOT NULL DEFAULT 0,
    carried_over_days DECIMAL(5,1) NOT NULL DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted_at DATETIME NULL,
    deleted_by BIGINT NULL,
    INDEX idx_hr_leave_balances_workspace (workspace_id),
    INDEX idx_hr_leave_balances_employee (employee_id),
    INDEX idx_hr_leave_balances_type (leave_type_id),
    INDEX idx_hr_leave_balances_year (employee_id, request_year),
    CONSTRAINT fk_hr_leave_balances_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id),
    CONSTRAINT fk_hr_leave_balances_employee FOREIGN KEY (employee_id) REFERENCES hr_employees(id),
    CONSTRAINT fk_hr_leave_balances_type FOREIGN KEY (leave_type_id) REFERENCES hr_leave_types(id),
    UNIQUE KEY uk_hr_leave_balances_emp_type_year (employee_id, leave_type_id, request_year)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- HR Leave Requests
CREATE TABLE IF NOT EXISTS hr_leave_requests (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    workspace_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    leave_type_id BIGINT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    total_days DECIMAL(5,1) NOT NULL,
    reason TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    approved_by BIGINT NULL,
    approved_at DATETIME NULL,
    rejection_reason TEXT,
    cancelled_at DATETIME NULL,
    cancelled_by BIGINT NULL,
    request_year INT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted_at DATETIME NULL,
    deleted_by BIGINT NULL,
    INDEX idx_hr_leave_requests_workspace (workspace_id),
    INDEX idx_hr_leave_requests_employee (employee_id),
    INDEX idx_hr_leave_requests_type (leave_type_id),
    INDEX idx_hr_leave_requests_status (workspace_id, status),
    INDEX idx_hr_leave_requests_dates (start_date, end_date),
    INDEX idx_hr_leave_requests_pending (workspace_id, status, start_date),
    CONSTRAINT fk_hr_leave_requests_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id),
    CONSTRAINT fk_hr_leave_requests_employee FOREIGN KEY (employee_id) REFERENCES hr_employees(id),
    CONSTRAINT fk_hr_leave_requests_type FOREIGN KEY (leave_type_id) REFERENCES hr_leave_types(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
