package com.vinncorp.erp.modules.workflow.engine;

public enum WorkflowTrigger {
TASK_CREATED, TASK_UPDATED, TASK_COMPLETED, TASK_ASSIGNED, TASK_OVERDUE, SPRINT_STARTED, SPRINT_COMPLETED, DEPENDENCY_BLOCKED, DEPENDENCY_UNBLOCKED, COMMENT_ADDED, TIMELOG_CREATED} 