package com.vinncorp.erp.platform.notification.enums;

public enum NotificationType {
TASK_ASSIGNED, TASK_UNASSIGNED, STATUS_CHANGED, COMMENT_MENTION, COMMENT_REPLY, DUE_SOON, DUE_OVERDUE, FILE_UPLOADED, PROJECT_INVITE, DEADLINE_APPROACHING, OWNERSHIP_CHANGED, RECURRING_TASK_GENERATED, RECURRENCE_PAUSED, RECURRENCE_STOPPED, AUTOMATION_TRIGGERED, AUTOMATION_FAILED, SLA_BREACHED, SLA_WARNING, TASK_ESCALATED, SMART_ASSIGNMENT, EXECUTION_RISK, DELIVERY_DELAY, SPRINT_OVERLOAD, CRITICAL_PATH_ALERT, LEAVE_REQUESTED, LEAVE_APPROVED, LEAVE_REJECTED, LEAVE_CANCELLED} 